# Generated by Django 5.0.4 on 2024-04-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "attachmentid",
                    models.AutoField(
                        db_column="attachmentId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "attachmentblob",
                    models.TextField(blank=True, db_column="attachmentBlob", null=True),
                ),
            ],
            options={
                "db_table": "Attachment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="userId", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(db_column="userName", max_length=255)),
                ("firstname", models.CharField(db_column="firstName", max_length=255)),
                ("lastname", models.CharField(db_column="lastName", max_length=255)),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "categoryid",
                    models.AutoField(
                        db_column="categoryId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "categoryname",
                    models.CharField(db_column="categoryName", max_length=255),
                ),
            ],
            options={
                "db_table": "Category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "email",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Credentials",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Monthlycategorybudget",
            fields=[
                (
                    "budgetid",
                    models.AutoField(
                        db_column="budgetId", primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("month", models.DateField()),
            ],
            options={
                "db_table": "MonthlyCategoryBudget",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Split",
            fields=[
                (
                    "splitid",
                    models.AutoField(
                        db_column="splitId", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Split",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "txnid",
                    models.AutoField(
                        db_column="txnId", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "paymentmethod",
                    models.CharField(
                        blank=True, db_column="paymentMethod", max_length=255, null=True
                    ),
                ),
                ("type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Transaction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Borrows",
            fields=[
                (
                    "borrowerid",
                    models.OneToOneField(
                        db_column="borrowerId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="webapp.user",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=2, max_digits=10
                    ),
                ),
                ("ispaid", models.IntegerField(db_column="isPaid")),
            ],
            options={
                "db_table": "Borrows",
                "managed": False,
            },
        ),
    ]
